#!/usr/bin/env bash
# 前端构建脚本 — 用于 Cloudflare Pages 部署
# 将 API_BASE_URL 环境变量写入 public/config.js

set -e

API_URL="${API_BASE_URL:-}"

if [ -z "$API_URL" ]; then
  echo "WARNING: API_BASE_URL is not set, frontend will try same-origin API calls."
  echo "Set API_BASE_URL in Cloudflare Pages environment variables (e.g. https://llm-nav-api.onrender.com)"
fi

# 写入 config.js
cat > public/config.js << EOF
// Auto-generated by build-frontend.sh — do not edit manually
// API 后端地址，由 Cloudflare Pages 环境变量注入
window.API_BASE = '${API_URL}';
EOF

echo "config.js generated: API_BASE = '${API_URL}'"
