-- 第二批运营扩充：围绕“聚合中转站”定位补充更多可访问的服务商。
INSERT OR IGNORE INTO brands (name) VALUES
('OpenAI'),
('Anthropic'),
('Google'),
('DeepSeek'),
('xAI'),
('Alibaba'),
('Moonshot');

INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
) VALUES
('topapi', 'TopAPI', '#0F766E', '聚合中转',
 '通用 AI API 聚合入口，面向需要统一调用多品牌模型的开发者和团队，适合作为 OpenAI 兼容接入备选。',
 '["OpenAI","Anthropic","Google","DeepSeek","xAI"]',
 '["多模型统一入口","OpenAI 兼容格式","适合开发者接入","覆盖主流模型","文档入口清晰"]',
 'ok', '', 'https://api.topopenai.com/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Grok 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('gotoken-ai', 'Gotoken', '#2563EB', '聚合中转',
 'AI 大模型 API 中转平台，覆盖 GPT、Claude、Grok、Gemini 等模型，适合需要多模型统一试用和调用的项目。',
 '["OpenAI","Anthropic","Google","DeepSeek","xAI"]',
 '["多模型覆盖","统一 API 入口","中文页面","适合小额测试","支持常见模型调用"]',
 'ok', '', 'https://gotoken.ai/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Grok 系列"]', '通用', 0,
 'ok', datetime('now','localtime'), 200, 0),

('openmodel', 'OpenModel', '#7C3AED', '聚合中转',
 '面向开发者的模型调用文档与聚合入口，适合需要通过统一文档快速接入多模型能力的团队。',
 '["OpenAI","Anthropic","Google","DeepSeek"]',
 '["文档入口清晰","多模型接入","面向开发集成","统一调用说明","适合评估测试"]',
 'ok', '', 'https://docs.openmodel.ai/en/docs/getting-started/introduction', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('apikl', 'API 快连', '#EA580C', '聚合中转',
 'AI API 快速接入服务入口，适合个人开发者和团队快速完成多模型测试、调用和应用集成。',
 '["OpenAI","Anthropic","Google","DeepSeek"]',
 '["快速接入","多模型聚合","中文服务页面","适合开发者测试","按需调用"]',
 'ok', '', 'https://apikl.ai/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('apizhongzhuan', 'API中转站', '#DC2626', '聚合中转',
 'AI 大模型 API 中转聚合平台，适合需要统一入口、低门槛测试和多模型调用的开发者。',
 '["OpenAI","Anthropic","Google","DeepSeek"]',
 '["大模型聚合","统一接口","低门槛测试","中文页面","支持主流模型"]',
 'ok', '', 'https://apizhongzhuan.cn/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('apimarket-cn', 'API Market', '#0EA5E9', '聚合中转',
 'AI 大模型 API 聚合平台，提供全球主流模型的统一入口，适合需要集中比较和调用多模型的团队。',
 '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
 '["全球模型聚合","统一调用入口","面向团队","模型覆盖较广","适合产品接入"]',
 'ok', '', 'https://apimarket.com.cn/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]', '通用', 0,
 'ok', datetime('now','localtime'), 200, 0),

('yunwu-api', '云雾 API', '#64748B', '聚合中转',
 'AI API 聚合服务入口，覆盖 Claude、GPT、Gemini 等模型，适合需要中文页面和多模型统一调用的用户。',
 '["OpenAI","Anthropic","Google","DeepSeek"]',
 '["多模型覆盖","中文页面","统一 API 入口","适合个人与团队","支持主流模型"]',
 'ok', '', 'https://yunwuapi.cloud/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列"]', '通用', 0,
 'ok', datetime('now','localtime'), 200, 0),

('uniapi', 'UniAPI', '#16A34A', '聚合中转',
 '提供 OpenAI、Gemini、Claude 等模型调用说明的聚合入口，适合需要统一调用格式和文档参考的开发者。',
 '["OpenAI","Anthropic","Google"]',
 '["调用说明清晰","多模型支持","统一接入","适合开发者","文档化入口"]',
 'ok', '', 'https://docs.uniapi.ai/docs/use/api', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('shanyiapi', 'ShanYi API', '#9333EA', '聚合中转',
 '面向 AI 模型调用的 API 服务入口，适合希望通过文档快速了解接入方式和可用模型的开发者。',
 '["OpenAI","Anthropic","Google","DeepSeek"]',
 '["文档入口","多模型调用","适合开发集成","统一服务入口","支持常见模型"]',
 'ok', '', 'https://docs.shanyiapi.com/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列"]', '个人开发者', 0,
 'ok', datetime('now','localtime'), 200, 0),

('uaiapi', 'UAIAPI', '#111827', '聚合中转',
 '统一 AI 模型 API 网关，适合需要通过一个入口接入多类模型能力的个人开发者和团队。',
 '["OpenAI","Anthropic","Google","DeepSeek","Moonshot"]',
 '["统一模型入口","多模型聚合","适合开发者接入","覆盖主流模型","按需调用"]',
 'ok', '', 'https://uaiapi.com/', 1, '', '', 0, 'pay_as_you_go',
 '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Kimi 系列"]', '通用', 0,
 'ok', datetime('now','localtime'), 200, 0);
