-- 150 冲刺批次：来自公开中转站榜单候选，已做基础可访问性确认。
INSERT OR IGNORE INTO brands (name) VALUES
('OpenAI'),
('Anthropic'),
('Google'),
('DeepSeek'),
('Alibaba');

WITH new_providers(id, name, url, color) AS (
  VALUES
  ('api-yuboar-com', 'api.yuboar.com', 'https://api.yuboar.com/', '#2563EB'),
  ('seesaw2ai-com', 'seesaw2ai.com', 'https://seesaw2ai.com/', '#7C3AED'),
  ('tenzen-ai', 'tenzen.ai', 'https://tenzen.ai/', '#0EA5E9'),
  ('newapi-diffusion-kurtisasia-com', 'newapi.diffusion.kurtisasia.com', 'https://newapi.diffusion.kurtisasia.com/', '#16A34A'),
  ('newapsu-com', 'newapsu.com', 'https://newapsu.com/', '#EA580C'),
  ('api-code-relay-com', 'api.code-relay.com', 'https://api.code-relay.com/', '#DC2626'),
  ('tokenharbor-ai', 'tokenharbor.ai', 'https://tokenharbor.ai/', '#0F766E'),
  ('nexaxis-ai', 'nexaxis.ai', 'https://nexaxis.ai/', '#9333EA'),
  ('apiclaude-cc', 'apiclaude.cc', 'https://apiclaude.cc/', '#2563EB'),
  ('kjapi-botsmart-net', 'kjapi.botsmart.net', 'https://kjapi.botsmart.net/', '#7C3AED'),
  ('timicc-com', 'timicc.com', 'https://timicc.com/', '#0EA5E9'),
  ('dmxapi-cn', 'dmxapi.cn', 'https://www.dmxapi.cn/', '#16A34A'),
  ('ai-tsapi-fun', 'ai.tsapi.fun', 'https://ai.tsapi.fun/', '#EA580C'),
  ('api-llm-token-cn', 'api.llm-token.cn', 'https://api.llm-token.cn/', '#DC2626'),
  ('codex-dakeai-cc', 'codex.dakeai.cc', 'https://codex.dakeai.cc/', '#0F766E'),
  ('aig888-com', 'aig888.com', 'https://www.aig888.com/', '#9333EA'),
  ('xinyuanai666-com', 'xinyuanai666.com', 'https://xinyuanai666.com/', '#2563EB'),
  ('ai-zan-top', 'ai.zan.top', 'https://ai.zan.top/', '#7C3AED'),
  ('hboom-ai', 'hboom.ai', 'https://hboom.ai/', '#0EA5E9'),
  ('happycode-vip', 'happycode.vip', 'https://happycode.vip/', '#16A34A'),
  ('easyrouter-io', 'easyrouter.io', 'https://easyrouter.io/', '#EA580C'),
  ('poloapi-top', 'poloapi.top', 'https://poloapi.top/', '#DC2626'),
  ('api-haimaker-ai', 'api.haimaker.ai', 'https://api.haimaker.ai/', '#0F766E'),
  ('opencc-281023-xyz', 'opencc.281023.xyz', 'https://opencc.281023.xyz/', '#9333EA'),
  ('sudocode-us', 'sudocode.us', 'https://www.sudocode.us/', '#2563EB'),
  ('ai-shi-guang-me', 'ai.shi-guang.me', 'https://ai.shi-guang.me/', '#7C3AED'),
  ('apinebula-com', 'apinebula.com', 'https://apinebula.com/', '#0EA5E9'),
  ('aiplatform-njsrd-com', 'aiplatform.njsrd.com', 'https://aiplatform.njsrd.com/', '#16A34A'),
  ('api-gateway-cersoft-com', 'api-gateway.cersoft.com', 'https://api-gateway.cersoft.com/', '#EA580C'),
  ('snap2fast-com', 'snap2fast.com', 'https://snap2fast.com/', '#DC2626'),
  ('api-tokendun-com', 'api.tokendun.com', 'https://api.tokendun.com/', '#0F766E'),
  ('llm-api-net', 'llm-api.net', 'https://llm-api.net/', '#9333EA'),
  ('api-slb-packyapi-com', 'api-slb.packyapi.com', 'https://api-slb.packyapi.com/', '#2563EB'),
  ('api-winfull-cloud-ip-cc', 'api.winfull.cloud-ip.cc', 'https://api.winfull.cloud-ip.cc/', '#7C3AED'),
  ('api-chatanywhere-tech', 'api.chatanywhere.tech', 'https://api.chatanywhere.tech/', '#0EA5E9'),
  ('ai47api-com', 'ai47api.com', 'https://ai47api.com/', '#16A34A'),
  ('passion8-cc', 'passion8.cc', 'https://passion8.cc/', '#EA580C'),
  ('wawapi-top', 'wawapi.top', 'https://wawapi.top/', '#DC2626'),
  ('dasuapi-com', 'dasuapi.com', 'https://dasuapi.com/', '#0F766E'),
  ('ssnaiyun-com', 'ssnaiyun.com', 'https://ssnaiyun.com/', '#9333EA'),
  ('gwlink-cc', 'gwlink.cc', 'https://gwlink.cc/', '#2563EB'),
  ('9527code-com', '9527code.com', 'https://9527code.com/', '#7C3AED'),
  ('xbhuiz-com', 'xbhuiz.com', 'https://xbhuiz.com/', '#0EA5E9'),
  ('api-loomcode-cn', 'api.loomcode.cn', 'https://api.loomcode.cn/', '#16A34A'),
  ('ai-furry-edu-gr', 'ai.furry.edu.gr', 'https://ai.furry.edu.gr/', '#EA580C'),
  ('zivv-pro', 'zivv.pro', 'https://zivv.pro/', '#DC2626'),
  ('officesai-top', 'officesai.top', 'https://officesai.top/', '#0F766E'),
  ('api-touken-pro', 'api.touken.pro', 'https://api.touken.pro/', '#9333EA'),
  ('linkai-shop', 'linkai.shop', 'https://linkai.shop/', '#2563EB'),
  ('api-xqlbest-com', 'api.xqlbest.com', 'https://api.xqlbest.com/', '#7C3AED'),
  ('api-fluxnode-org', 'api.fluxnode.org', 'https://api.fluxnode.org/', '#0EA5E9'),
  ('daodunapi-com', 'daodunapi.com', 'https://daodunapi.com/', '#16A34A'),
  ('api-999555999-com', 'api.999555999.com', 'https://api.999555999.com/', '#EA580C'),
  ('apishop-org', 'apishop.org', 'https://apishop.org/', '#DC2626'),
  ('max20-cn', 'max20.cn', 'https://max20.cn/', '#0F766E'),
  ('api-qingyangwanxi-cn', 'api.qingyangwanxi.cn', 'https://api.qingyangwanxi.cn/', '#9333EA'),
  ('zz-aigm99-cn', 'zz.aigm99.cn', 'https://zz.aigm99.cn/', '#2563EB'),
  ('codex-ccthl-com', 'codex.ccthl.com', 'https://codex.ccthl.com/', '#7C3AED'),
  ('api-toupiaoai-com', 'api.toupiaoai.com', 'https://api.toupiaoai.com/', '#0EA5E9'),
  ('sub2api-closeapi-top', 'sub2api.closeapi.top', 'https://sub2api.closeapi.top/', '#16A34A'),
  ('top-taluna-ai', 'top.taluna.ai', 'https://top.taluna.ai/', '#EA580C'),
  ('lmxu-cc', 'lmxu.cc', 'https://lmxu.cc/', '#DC2626'),
  ('api-zetatechs-com', 'api.zetatechs.com', 'https://api.zetatechs.com/', '#0F766E'),
  ('liantongapi-com', 'liantongapi.com', 'https://liantongapi.com/', '#9333EA'),
  ('aheapi-com', 'aheapi.com', 'https://aheapi.com/', '#2563EB'),
  ('api-clawsocket-com', 'api.clawsocket.com', 'https://api.clawsocket.com/', '#7C3AED'),
  ('api-slb-micuapi-ai', 'api-slb.micuapi.ai', 'https://api-slb.micuapi.ai/', '#0EA5E9'),
  ('xingwan-store', 'xingwan.store', 'https://xingwan.store/', '#16A34A'),
  ('multiai-store', 'multiai.store', 'https://multiai.store/', '#EA580C'),
  ('yizhinengai-com', 'yizhinengai.com', 'https://yizhinengai.com/', '#DC2626'),
  ('heyroute-ai', 'heyroute.ai', 'https://heyroute.ai/', '#0F766E'),
  ('sub-callai-one', 'sub.callai.one', 'https://sub.callai.one/', '#9333EA'),
  ('api-86gamestore-com', 'api.86gamestore.com', 'https://api.86gamestore.com/', '#2563EB'),
  ('ai-axzt-top', 'ai.axzt.top', 'https://ai.axzt.top/', '#7C3AED'),
  ('api-bblabu-cn', 'api.bblabu.cn', 'https://api.bblabu.cn/', '#0EA5E9'),
  ('api-codeyizhan-com', 'api.codeyizhan.com', 'https://api.codeyizhan.com/', '#16A34A'),
  ('akucb-com', 'akucb.com', 'https://www.akucb.com/', '#EA580C'),
  ('aigc-x-see-cn', 'aigc.x-see.cn', 'https://aigc.x-see.cn/', '#DC2626'),
  ('koalaapi-com', 'koalaapi.com', 'https://koalaapi.com/', '#0F766E'),
  ('api-apiyi-com', 'api.apiyi.com', 'https://api.apiyi.com/', '#9333EA'),
  ('api-147ai-cn', 'api.147ai.cn', 'https://api.147ai.cn/', '#2563EB'),
  ('llm-mathmodel-tech', 'llm.mathmodel.tech', 'https://llm.mathmodel.tech/', '#7C3AED'),
  ('nikoapi-xyz', 'nikoapi.xyz', 'https://nikoapi.xyz/', '#0EA5E9'),
  ('new-hahajimi-top', 'new.hahajimi.top', 'https://new.hahajimi.top/', '#16A34A'),
  ('api-1024token-xyz', 'api.1024token.xyz', 'https://api.1024token.xyz/', '#EA580C'),
  ('console-qqqrouter-ai', 'console.qqqrouter.ai', 'https://console.qqqrouter.ai/', '#DC2626'),
  ('yunwu-ai', 'yunwu.ai', 'https://yunwu.ai/', '#0F766E'),
  ('zenmux-ai', 'zenmux.ai', 'https://zenmux.ai/', '#9333EA'),
  ('iai-iisbo-com', 'iai.iisbo.com', 'https://iai.iisbo.com/', '#2563EB'),
  ('api-rcouyi-com', 'api.rcouyi.com', 'https://api.rcouyi.com/', '#7C3AED'),
  ('sparkcode-top', 'sparkcode.top', 'https://sparkcode.top/', '#0EA5E9'),
  ('suapi-cc', 'suapi.cc', 'https://suapi.cc/', '#16A34A')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
