-- 200 冲刺批次：来自公开中转站导航分页，已做基础可访问性确认。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('nekocode-ai', 'nekocode.ai', 'https://nekocode.ai/', '#2563EB'),
  ('us-ai-yswuxian-com', 'us.ai.yswuxian.com', 'https://us.ai.yswuxian.com/', '#7C3AED'),
  ('kelaiapi-cc', 'kelaiapi.cc', 'https://kelaiapi.cc/', '#0EA5E9'),
  ('api-portunex-gewulabs-group', 'api.portunex.gewulabs.group', 'https://api.portunex.gewulabs.group/', '#16A34A'),
  ('code-wearekna-com', 'code.wearekna.com', 'https://code.wearekna.com/', '#EA580C'),
  ('api-qlqq-de', 'api.qlqq.de', 'https://api.qlqq.de/', '#DC2626'),
  ('api-api2cn-com', 'api.api2cn.com', 'https://api.api2cn.com/', '#0F766E'),
  ('api-vllmproxy-com', 'api.vllmproxy.com', 'https://api.vllmproxy.com/', '#9333EA'),
  ('poloai-top', 'poloai.top', 'https://poloai.top/', '#2563EB'),
  ('openrouter-my', 'openrouter.my', 'https://openrouter.my/', '#7C3AED'),
  ('emengai-com', 'emengai.com', 'https://emengai.com/', '#0EA5E9'),
  ('api-aircode-vip', 'api.aircode.vip', 'https://api.aircode.vip/', '#16A34A'),
  ('api-poixe-com', 'api.poixe.com', 'https://api.poixe.com/', '#EA580C'),
  ('mikuapi-org', 'mikuapi.org', 'https://mikuapi.org/', '#DC2626'),
  ('dawclaudecode-com', 'dawclaudecode.com', 'https://dawclaudecode.com/', '#0F766E'),
  ('api-loveapi-cc', 'api.loveapi.cc', 'https://api.loveapi.cc/', '#9333EA'),
  ('api-tokeng0d-com', 'api.tokeng0d.com', 'https://api.tokeng0d.com/', '#2563EB'),
  ('taffy-work', 'taffy.work', 'https://taffy.work/', '#7C3AED'),
  ('ccgoai-com', 'ccgoai.com', 'https://www.ccgoai.com/', '#0EA5E9'),
  ('easyapis-cc', 'easyapis.cc', 'https://easyapis.cc/', '#16A34A'),
  ('api-fullcupai-com', 'api.fullcupai.com', 'https://api.fullcupai.com/', '#EA580C'),
  ('ai-deepthink-works', 'ai.deepthink.works', 'https://ai.deepthink.works/', '#DC2626'),
  ('api-mosshubs-com', 'api.mosshubs.com', 'https://api.mosshubs.com/', '#0F766E'),
  ('ssnaicloud-com', 'ssnaicloud.com', 'https://ssnaicloud.com/', '#9333EA'),
  ('api-rootflowai-com', 'api.rootflowai.com', 'https://api.rootflowai.com/', '#2563EB'),
  ('anyplan-cn', 'anyplan.cn', 'https://anyplan.cn/', '#7C3AED'),
  ('api-constreet-cc', 'api.constreet.cc', 'https://api.constreet.cc/', '#0EA5E9'),
  ('api-bianxie-ai', 'api.bianxie.ai', 'https://api.bianxie.ai/', '#16A34A'),
  ('xingsuancode-ai', 'xingsuancode.ai', 'https://xingsuancode.ai/', '#EA580C'),
  ('anyfast-ai', 'anyfast.ai', 'https://www.anyfast.ai/', '#DC2626'),
  ('api-kourichat-com', 'api.kourichat.com', 'https://api.kourichat.com/', '#0F766E'),
  ('api-968api-com', 'api.968api.com', 'https://api.968api.com/', '#9333EA'),
  ('api-ooapi-cc', 'api.ooapi.cc', 'https://api.ooapi.cc/', '#2563EB'),
  ('api-bawanglong-xyz', 'api.bawanglong.xyz', 'https://api.bawanglong.xyz/', '#7C3AED'),
  ('clauddy-com', 'clauddy.com', 'https://clauddy.com/', '#0EA5E9'),
  ('api-aixiaobai-pro', 'api.aixiaobai.pro', 'https://api.aixiaobai.pro/', '#16A34A'),
  ('ai-chaozhi-chat', 'ai.chaozhi.chat', 'https://ai.chaozhi.chat/', '#EA580C'),
  ('openflare-ai', 'openflare.ai', 'https://openflare.ai/', '#DC2626'),
  ('api-codelife-eu-cc', 'api.codelife.eu.cc', 'https://api.codelife.eu.cc/', '#0F766E'),
  ('api-bestcodex-xyz', 'api.bestcodex.xyz', 'https://api.bestcodex.xyz/', '#9333EA'),
  ('api-juhecode-cn', 'api.juhecode.cn', 'https://api.juhecode.cn/', '#2563EB'),
  ('api-relaypool-cam', 'api.relaypool.cam', 'https://api.relaypool.cam/', '#7C3AED'),
  ('api-witflow-ai', 'api.witflow.ai', 'https://api.witflow.ai/', '#0EA5E9'),
  ('app-routifyapi-com', 'app.routifyapi.com', 'https://app.routifyapi.com/', '#16A34A'),
  ('b-kr777-top', 'b.kr777.top', 'https://b.kr777.top/', '#EA580C'),
  ('cc-nuoda-vip', 'cc.nuoda.vip', 'https://cc.nuoda.vip/', '#DC2626'),
  ('chat-ekti-cc', 'chat.ekti.cc', 'https://chat.ekti.cc/', '#0F766E'),
  ('cosin-ai', 'cosin.ai', 'https://cosin.ai/', '#9333EA'),
  ('dltokenapi-com', 'dltokenapi.com', 'https://dltokenapi.com/', '#2563EB'),
  ('e7y-com', 'e7y.com', 'https://e7y.com/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
