-- 250 冲刺批次：来自公开中转站导航分页，已做基础可访问性确认。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('api-pateway-ai', 'api.pateway.ai', 'https://api.pateway.ai/', '#2563EB'),
  ('api-iiiiitoken-com', 'api.iiiiitoken.com', 'https://api.iiiiitoken.com/', '#7C3AED'),
  ('api-neorouter-ai', 'api.neorouter.ai', 'https://api.neorouter.ai/', '#0EA5E9'),
  ('api-ohmygpt-com', 'api.ohmygpt.com', 'https://api.ohmygpt.com/', '#16A34A'),
  ('api-api2gpt-com', 'api.api2gpt.com', 'https://api.api2gpt.com/', '#EA580C'),
  ('api-koozhan-com', 'api.koozhan.com', 'https://api.koozhan.com/', '#DC2626'),
  ('api-tenzen-ai', 'api.tenzen.ai', 'https://api.tenzen.ai/', '#0F766E'),
  ('9527code-com', '9527code.com', 'https://www.9527code.com/', '#9333EA'),
  ('api-hao-ai', 'api.hao.ai', 'https://api.hao.ai/', '#2563EB'),
  ('api-aijws-com', 'api.aijws.com', 'https://api.aijws.com/', '#7C3AED'),
  ('api-aigocode-app', 'api.aigocode.app', 'https://api.aigocode.app/', '#0EA5E9'),
  ('minkanashenawu-com', 'minkanashenawu.com', 'http://minkanashenawu.com/', '#16A34A'),
  ('api-b-ai', 'api.b.ai', 'https://api.b.ai/', '#EA580C'),
  ('api-apib-ai', 'api.apib.ai', 'https://api.apib.ai/', '#DC2626'),
  ('justapi-cn', 'justapi.cn', 'https://justapi.cn/', '#0F766E'),
  ('koozhan-com', 'koozhan.com', 'https://koozhan.com/', '#9333EA'),
  ('router-zillion-network', 'router.zillion.network', 'https://router.zillion.network/', '#2563EB'),
  ('sub2api-52ai-pro', 'sub2api.52ai.pro', 'https://sub2api.52ai.pro/', '#7C3AED'),
  ('test-api-770220-xyz', 'test.api.770220.xyz', 'https://test.api.770220.xyz/', '#0EA5E9'),
  ('tokenspace-cloud', 'tokenspace.cloud', 'https://tokenspace.cloud/', '#16A34A'),
  ('wintoken-dev', 'wintoken.dev', 'https://wintoken.dev/', '#EA580C'),
  ('91code-ai', '91code.ai', 'https://www.91code.ai/', '#DC2626'),
  ('chirouai-com', 'chirouai.com', 'https://www.chirouai.com/', '#0F766E'),
  ('pivothub-ai', 'pivothub.ai', 'https://www.pivothub.ai/', '#9333EA'),
  ('xixiapi-cc', 'xixiapi.cc', 'https://xixiapi.cc/', '#2563EB'),
  ('yuandianapi-com', 'yuandianapi.com', 'https://yuandianapi.com/', '#7C3AED'),
  ('ai-cloxl-com', 'ai.cloxl.com', 'https://ai.cloxl.com/', '#0EA5E9'),
  ('ai-ovocloud-vip', 'ai.ovocloud.vip', 'https://ai.ovocloud.vip/', '#16A34A'),
  ('api-best-iksvip-cc', 'api-best.iksvip.cc', 'https://api-best.iksvip.cc/', '#EA580C'),
  ('api-aig-ai-com', 'api.aig-ai.com', 'https://api.aig-ai.com/', '#DC2626'),
  ('api-hyhawang-com', 'api.hyhawang.com', 'https://api.hyhawang.com/', '#0F766E'),
  ('api-qianmian-ai', 'api.qianmian.ai', 'https://api.qianmian.ai/', '#9333EA'),
  ('api-tallius-ai', 'api.tallius.ai', 'https://api.tallius.ai/', '#2563EB'),
  ('api-yunnet-top', 'api.yunnet.top', 'https://api.yunnet.top/', '#7C3AED'),
  ('api-zeropre-xyz', 'api.zeropre.xyz', 'https://api.zeropre.xyz/', '#0EA5E9'),
  ('api-zwenooo-link', 'api.zwenooo.link', 'https://api.zwenooo.link/', '#16A34A'),
  ('apipros-cc', 'apipros.cc', 'https://apipros.cc/', '#EA580C'),
  ('newapi-ailyyzdk-xyz', 'newapi.ailyyzdk.xyz', 'https://newapi.ailyyzdk.xyz/', '#DC2626'),
  ('openapi-junliai-com', 'openapi.junliai.com', 'https://openapi.junliai.com/', '#0F766E'),
  ('purerouter-xyz', 'purerouter.xyz', 'https://purerouter.xyz/', '#9333EA'),
  ('elbnt-ai', 'elbnt.ai', 'https://www.elbnt.ai/', '#2563EB'),
  ('tokenopen-ai', 'tokenopen.ai', 'https://www.tokenopen.ai/', '#7C3AED'),
  ('ai-tob-twskyhope-top', 'ai-tob.twskyhope.top', 'https://ai-tob.twskyhope.top/', '#0EA5E9'),
  ('cloud-dataeyes-ai', 'cloud.dataeyes.ai', 'https://cloud.dataeyes.ai/', '#16A34A'),
  ('api-oaipro-com', 'api.oaipro.com', 'https://api.oaipro.com/', '#EA580C'),
  ('api-uniapi-io', 'api.uniapi.io', 'https://api.uniapi.io/', '#DC2626'),
  ('safeapi-my', 'safeapi.my', 'https://safeapi.my/', '#0F766E'),
  ('saferouter-my', 'saferouter.my', 'https://saferouter.my/', '#9333EA'),
  ('liliapi-siphot-com', 'liliapi.siphot.com', 'https://liliapi.siphot.com/', '#2563EB'),
  ('ai-key-cc', 'ai-key.cc', 'https://ai-key.cc/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
