-- 300 冲刺批次：补足前台展示数到 300，剔除临时测试域名和明显重复项。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('sub2-congmingai-com', 'sub2.congmingai.com', 'https://sub2.congmingai.com/', '#2563EB'),
  ('anpin-ai', 'anpin.ai', 'https://anpin.ai/', '#7C3AED'),
  ('platform-modelapi-ai', 'platform.modelapi.ai', 'https://platform.modelapi.ai/', '#0EA5E9'),
  ('token-sanlingsk-com', 'token.sanlingsk.com', 'https://token.sanlingsk.com/', '#16A34A'),
  ('pure100-org', 'pure100.org', 'https://www.pure100.org/', '#EA580C'),
  ('modcon-top', 'modcon.top', 'https://modcon.top/', '#DC2626'),
  ('sudocode-run', 'sudocode.run', 'https://sudocode.run/', '#0F766E'),
  ('tokenrun-org', 'tokenrun.org', 'https://tokenrun.org/', '#9333EA'),
  ('layer4-cc', 'layer4.cc', 'https://layer4.cc/', '#2563EB'),
  ('118-ink', '118.ink', 'https://118.ink/', '#7C3AED'),
  ('ai-yxkl-cloud', 'ai.yxkl.cloud', 'https://ai.yxkl.cloud/', '#0EA5E9'),
  ('api-aigocode-com', 'api.aigocode.com', 'https://api.aigocode.com/', '#16A34A'),
  ('api-chiyicn-com', 'api.chiyicn.com', 'https://api.chiyicn.com/', '#EA580C'),
  ('fushengyunsuan-cn', 'fushengyunsuan.cn', 'https://fushengyunsuan.cn/', '#DC2626'),
  ('api-inputapi-com', 'api.inputapi.com', 'https://api.inputapi.com/', '#0F766E'),
  ('cc-zhihuiapi-top', 'cc.zhihuiapi.top', 'https://cc.zhihuiapi.top/', '#9333EA'),
  ('jyuan-uk', 'jyuan.uk', 'https://jyuan.uk/', '#2563EB'),
  ('viptokens-net', 'viptokens.net', 'https://viptokens.net/', '#7C3AED'),
  ('zzmapi-zzmsgdsg-xyz', 'zzmapi.zzmsgdsg.xyz', 'https://zzmapi.zzmsgdsg.xyz/', '#0EA5E9'),
  ('okmcode-com', 'okmcode.com', 'https://okmcode.com/', '#16A34A'),
  ('soul-mixiaoxiao-com', 'soul.mixiaoxiao.com', 'https://soul.mixiaoxiao.com/', '#EA580C'),
  ('nowcoding-ai', 'nowcoding.ai', 'https://nowcoding.ai/', '#DC2626'),
  ('uocode-com', 'uocode.com', 'https://www.uocode.com/', '#0F766E'),
  ('api-aspirin-cc', 'api.aspirin.cc', 'https://api.aspirin.cc/', '#9333EA'),
  ('micuapi-ai', 'micuapi.ai', 'https://www.micuapi.ai/', '#2563EB'),
  ('fkclaude-xyz', 'fkclaude.xyz', 'https://www.fkclaude.xyz/', '#7C3AED'),
  ('api-openai-proxy-org', 'api.openai-proxy.org', 'https://api.openai-proxy.org/', '#0EA5E9'),
  ('right-codes', 'right.codes', 'http://www.right.codes/', '#16A34A'),
  ('cctq-ai', 'cctq.ai', 'https://www.cctq.ai/', '#EA580C'),
  ('api-lmuai-com', 'api.lmuai.com', 'https://api.lmuai.com/', '#DC2626'),
  ('4router-net', '4router.net', 'https://4router.net/', '#0F766E'),
  ('llm-all-pro', 'llm-all.pro', 'https://llm-all.pro/', '#9333EA'),
  ('anyrouter-top', 'anyrouter.top', 'https://anyrouter.top/', '#2563EB'),
  ('bytego-team', 'bytego.team', 'https://www.bytego.team/', '#7C3AED'),
  ('api-routin-ai', 'api.routin.ai', 'https://api.routin.ai/', '#0EA5E9'),
  ('ai-sandboxai-top', 'ai.sandboxai.top', 'https://ai.sandboxai.top/', '#16A34A'),
  ('api-nycatai-com', 'api.nycatai.com', 'https://api.nycatai.com/', '#EA580C'),
  ('api-direct-ccapi-us', 'api-direct.ccapi.us', 'https://api-direct.ccapi.us/', '#DC2626'),
  ('ai-sectl-cn', 'ai.sectl.cn', 'https://ai.sectl.cn/', '#0F766E'),
  ('llmapi-paratera-com', 'llmapi.paratera.com', 'https://llmapi.paratera.com/', '#9333EA'),
  ('api-dorapenguin-top', 'api.dorapenguin.top', 'https://api.dorapenguin.top/', '#2563EB'),
  ('ai-hub-uk', 'ai-hub.uk', 'https://ai-hub.uk/', '#7C3AED'),
  ('tingbao-vip', 'tingbao.vip', 'https://tingbao.vip/', '#0EA5E9'),
  ('anyaigc-com', 'anyaigc.com', 'https://anyaigc.com/', '#16A34A'),
  ('api-nionio2026-xyz', 'api.nionio2026.xyz', 'https://api.nionio2026.xyz/', '#EA580C'),
  ('ccdox-0755-click', 'ccdox.0755.click', 'https://ccdox.0755.click/', '#DC2626'),
  ('mytokenpi-com', 'mytokenpi.com', 'https://mytokenpi.com/', '#0F766E'),
  ('claude-tokenscode-com', 'claude.tokenscode.com', 'https://claude.tokenscode.com/', '#9333EA'),
  ('api-codex-cn', 'api-codex.cn', 'https://www.api-codex.cn/', '#2563EB'),
  ('claude-shorekeeper-love', 'claude.shorekeeper.love', 'https://claude.shorekeeper.love/', '#7C3AED'),
  ('api-wankey-xyz', 'api.wankey.xyz', 'https://api.wankey.xyz/', '#0EA5E9')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
