-- 350 冲刺批次：继续扩充聚合中转站，优先选择更像正式服务入口的域名。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('south10032-xyz', 'south10032.xyz', 'https://south10032.xyz/', '#2563EB'),
  ('c-api-cc', 'c-api.cc', 'https://c-api.cc/', '#7C3AED'),
  ('sadai-cc', 'sadai.cc', 'https://sadai.cc/', '#0EA5E9'),
  ('api-aiai-bar', 'api.aiai.bar', 'https://api.aiai.bar/', '#16A34A'),
  ('api-cxalice-icu', 'api.cxalice.icu', 'https://api.cxalice.icu/', '#EA580C'),
  ('dazes-cc', 'dazes.cc', 'https://dazes.cc/', '#DC2626'),
  ('api-lukyface-com', 'api.lukyface.com', 'https://api.lukyface.com/', '#0F766E'),
  ('api-inprior-com', 'api.inprior.com', 'https://api.inprior.com/', '#9333EA'),
  ('tokencross-ai', 'tokencross.ai', 'https://tokencross.ai/', '#2563EB'),
  ('wawazz-xyz', 'wawazz.xyz', 'https://wawazz.xyz/', '#7C3AED'),
  ('ai2-rtoc-cc', 'ai2.rtoc.cc', 'https://ai2.rtoc.cc/', '#0EA5E9'),
  ('api-tyasai-com', 'api.tyasai.com', 'https://api.tyasai.com/', '#16A34A'),
  ('sk-free-com', 'sk-free.com', 'https://www.sk-free.com/', '#EA580C'),
  ('api-pptoken-org', 'api.pptoken.org', 'https://api.pptoken.org/', '#DC2626'),
  ('youmisub-cloud', 'youmisub.cloud', 'https://youmisub.cloud/', '#0F766E'),
  ('vip-xiaweiliang-cn', 'vip.xiaweiliang.cn', 'http://vip.xiaweiliang.cn/', '#9333EA'),
  ('api-cdn-apishop-org', 'api-cdn.apishop.org', 'https://api-cdn.apishop.org/', '#2563EB'),
  ('apivibecoding-com', 'apivibecoding.com', 'https://apivibecoding.com/', '#7C3AED'),
  ('api-unity2-ai', 'api.unity2.ai', 'https://api.unity2.ai/', '#0EA5E9'),
  ('claude-buzz7-top', 'claude.buzz7.top', 'https://claude.buzz7.top/', '#16A34A'),
  ('zz1cc-cc-cd', 'zz1cc.cc.cd', 'https://zz1cc.cc.cd/', '#EA580C'),
  ('api-vibe-subsapi-com', 'api.vibe-subsapi.com', 'https://api.vibe-subsapi.com/', '#DC2626'),
  ('lb7666-top', 'lb7666.top', 'https://lb7666.top/', '#0F766E'),
  ('api-kkrich-ltd', 'api.kkrich.ltd', 'https://api.kkrich.ltd/', '#9333EA'),
  ('ddshub-cc', 'ddshub.cc', 'https://www.ddshub.cc/', '#2563EB'),
  ('api-tianshux-com', 'api.tianshux.com', 'https://api.tianshux.com/', '#7C3AED'),
  ('api-botcf-com', 'api.botcf.com', 'https://api.botcf.com/', '#0EA5E9'),
  ('aiaiai-ruinet-work', 'aiaiai.ruinet.work', 'https://aiaiai.ruinet.work/', '#16A34A'),
  ('api-ai-vk168-top', 'api.ai.vk168.top', 'https://api.ai.vk168.top/', '#EA580C'),
  ('moxin-studio', 'moxin.studio', 'https://www.moxin.studio/', '#DC2626'),
  ('api-gpugeek-com', 'api.gpugeek.com', 'https://api.gpugeek.com/', '#0F766E'),
  ('rkapi-com', 'rkapi.com', 'https://rkapi.com/', '#9333EA'),
  ('sub2api-apizz-xyz', 'sub2api.apizz.xyz', 'https://sub2api.apizz.xyz/', '#2563EB'),
  ('maoapi-org', 'maoapi.org', 'https://maoapi.org/', '#7C3AED'),
  ('xmapi-site', 'xmapi.site', 'https://xmapi.site/', '#0EA5E9'),
  ('sub2api-luchikey-com', 'sub2api.luchikey.com', 'https://sub2api.luchikey.com/', '#16A34A'),
  ('dreamrouter-ai', 'dreamrouter.ai', 'https://dreamrouter.ai/', '#EA580C'),
  ('aifxo-com', 'aifxo.com', 'https://aifxo.com/', '#DC2626'),
  ('api-aispline-com', 'api.aispline.com', 'https://api.aispline.com/', '#0F766E'),
  ('api-enter9-de', 'api.enter9.de', 'https://api.enter9.de/', '#9333EA'),
  ('nyue-cc', 'nyue.cc', 'https://nyue.cc/', '#2563EB'),
  ('api-aiduck-fun', 'api.aiduck.fun', 'https://api.aiduck.fun/', '#7C3AED'),
  ('api-iotwq-top', 'api.iotwq.top', 'https://api.iotwq.top/', '#0EA5E9'),
  ('api-o77-top', 'api.o77.top', 'https://api.o77.top/', '#16A34A'),
  ('pixelstarrysky-xyz', 'pixelstarrysky.xyz', 'https://pixelstarrysky.xyz/', '#EA580C'),
  ('us-novaiapi-com', 'us.novaiapi.com', 'https://us.novaiapi.com/', '#DC2626'),
  ('upstream-chunxueai-com', 'upstream.chunxueai.com', 'https://upstream.chunxueai.com/', '#0F766E'),
  ('api-holdai-top', 'api.holdai.top', 'https://api.holdai.top/', '#9333EA'),
  ('api-solov-cc', 'api.solov.cc', 'https://api.solov.cc/', '#2563EB'),
  ('walkai-top', 'walkai.top', 'https://walkai.top/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
