-- 400 冲刺批次：继续扩充聚合中转站，跳过临时域名和不适合品牌展示的域名。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('moyuu-cc', 'moyuu.cc', 'https://moyuu.cc/', '#2563EB'),
  ('webclaw-bond', 'webclaw.bond', 'https://webclaw.bond/', '#7C3AED'),
  ('mdkj-lol', 'mdkj.lol', 'https://mdkj.lol/', '#0EA5E9'),
  ('sub1-happycoding-online', 'sub1.happycoding.online', 'https://sub1.happycoding.online/', '#16A34A'),
  ('api-feifeimiao-top', 'api.feifeimiao.top', 'https://api.feifeimiao.top/', '#EA580C'),
  ('fluxionai-space', 'fluxionai.space', 'https://fluxionai.space/', '#DC2626'),
  ('sub2api-info', 'sub2api.info', 'http://sub2api.info/', '#0F766E'),
  ('socheap-ai', 'socheap.ai', 'https://socheap.ai/', '#9333EA'),
  ('comeu-ai', 'comeu.ai', 'https://comeu.ai/', '#2563EB'),
  ('98api-top', '98api.top', 'https://98api.top/', '#7C3AED'),
  ('ai-hctopup-com', 'ai.hctopup.com', 'https://ai.hctopup.com/', '#0EA5E9'),
  ('coolmoai-cc', 'coolmoai.cc', 'https://coolmoai.cc/', '#16A34A'),
  ('ccapi-us', 'ccapi.us', 'https://ccapi.us/', '#EA580C'),
  ('allincode-top', 'allincode.top', 'https://allincode.top/', '#DC2626'),
  ('wangbuxie-xyz', 'wangbuxie.xyz', 'https://wangbuxie.xyz/', '#0F766E'),
  ('bs-gsykj-com', 'bs.gsykj.com', 'http://bs.gsykj.com/', '#9333EA'),
  ('xrok-dev', 'xrok.dev', 'https://xrok.dev/', '#2563EB'),
  ('eirouter-com', 'eirouter.com', 'https://www.eirouter.com/', '#7C3AED'),
  ('xiamiapi-xyz', 'xiamiapi.xyz', 'https://www.xiamiapi.xyz/', '#0EA5E9'),
  ('zweb-01yq888-com', 'zweb.01yq888.com', 'https://zweb.01yq888.com/', '#16A34A'),
  ('api-ofox-io', 'api.ofox.io', 'https://api.ofox.io/', '#EA580C'),
  ('vpsairobot-com', 'vpsairobot.com', 'https://vpsairobot.com/', '#DC2626'),
  ('ergouzi-life', 'ergouzi.life', 'https://ergouzi.life/', '#0F766E'),
  ('fucheers-top', 'fucheers.top', 'https://www.fucheers.top/', '#9333EA'),
  ('niffler-org', 'niffler.org', 'https://niffler.org/', '#2563EB'),
  ('4sapi-com', '4sapi.com', 'https://4sapi.com/', '#7C3AED'),
  ('switchbase-vip', 'switchbase.vip', 'https://switchbase.vip/', '#0EA5E9'),
  ('qweapi-com', 'qweapi.com', 'https://qweapi.com/', '#16A34A'),
  ('ai-dongli-work', 'ai.dongli.work', 'https://ai.dongli.work/', '#EA580C'),
  ('api-apistar-com-cn', 'api.apistar.com.cn', 'https://api.apistar.com.cn/', '#DC2626'),
  ('api-e2ez-com', 'api.e2ez.com', 'https://api.e2ez.com/', '#0F766E'),
  ('subrouter-ai', 'subrouter.ai', 'https://subrouter.ai/', '#9333EA'),
  ('ai-centos-hk', 'ai.centos.hk', 'https://ai.centos.hk/', '#2563EB'),
  ('chunfeng-mentalout-top', 'chunfeng.mentalout.top', 'https://chunfeng.mentalout.top/', '#7C3AED'),
  ('bmapi-020212-xyz', 'bmapi.020212.xyz', 'https://bmapi.020212.xyz/', '#0EA5E9'),
  ('yysc-top', 'yysc.top', 'https://www.yysc.top/', '#16A34A'),
  ('ai98pro-xyz', 'ai98pro.xyz', 'https://ai98pro.xyz/', '#EA580C'),
  ('inroi-shop', 'inroi.shop', 'https://www.inroi.shop/', '#DC2626'),
  ('suoxie-codes', 'suoxie.codes', 'https://suoxie.codes/', '#0F766E'),
  ('rehdasu-cn', 'rehdasu.cn', 'https://rehdasu.cn/', '#9333EA'),
  ('sub2-de5-net', 'sub2.de5.net', 'https://sub2.de5.net/', '#2563EB'),
  ('runapi-co', 'runapi.co', 'https://runapi.co/', '#7C3AED'),
  ('sub-deuo-top', 'sub.deuo.top', 'https://sub.deuo.top/', '#0EA5E9'),
  ('api-dreamaitoken-cloud', 'api.dreamaitoken.cloud', 'https://api.dreamaitoken.cloud/', '#16A34A'),
  ('sub2-yiyunweb-cloud', 'sub2.yiyunweb.cloud', 'https://sub2.yiyunweb.cloud/', '#EA580C'),
  ('ai-lazymo-qzz-io', 'ai.lazymo.qzz.io', 'https://ai.lazymo.qzz.io/', '#DC2626'),
  ('tokenadvent-com', 'tokenadvent.com', 'https://tokenadvent.com/', '#0F766E'),
  ('aicyy-xyz', 'aicyy.xyz', 'https://aicyy.xyz/', '#9333EA'),
  ('api-0029-org', 'api.0029.org', 'https://api.0029.org/', '#2563EB'),
  ('namax-ai', 'namax.ai', 'https://www.namax.ai/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
