-- 450 冲刺批次：继续扩充聚合中转站，避开临时入口和容易引起品牌误解的域名。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('aicodelink-top', 'aicodelink.top', 'https://aicodelink.top/', '#2563EB'),
  ('api-scienceedu-me', 'api.scienceedu.me', 'https://api.scienceedu.me/', '#7C3AED'),
  ('api-y2025g-top', 'api.y2025g.top', 'https://api.y2025g.top/', '#0EA5E9'),
  ('qilinapi-com', 'qilinapi.com', 'https://www.qilinapi.com/', '#16A34A'),
  ('aipi-talilosis-site', 'aipi.talilosis.site', 'https://aipi.talilosis.site/', '#EA580C'),
  ('hellox-cloud', 'hellox.cloud', 'https://www.hellox.cloud/', '#DC2626'),
  ('api-zzswitch-com', 'api.zzswitch.com', 'https://api.zzswitch.com/', '#0F766E'),
  ('zzshu-cc', 'zzshu.cc', 'https://zzshu.cc/', '#9333EA'),
  ('xuseny-online', 'xuseny.online', 'https://xuseny.online/', '#2563EB'),
  ('api-owlai-tech', 'api.owlai.tech', 'https://api.owlai.tech/', '#7C3AED'),
  ('shunfen6-win', 'shunfen6.win', 'https://shunfen6.win/', '#0EA5E9'),
  ('api-uzip-cn', 'api.uzip.cn', 'https://api.uzip.cn/', '#16A34A'),
  ('api-anbalu-top', 'api.anbalu.top', 'https://api.anbalu.top/', '#EA580C'),
  ('gptcodex-top', 'gptcodex.top', 'https://gptcodex.top/', '#DC2626'),
  ('codex-hiyo-top', 'codex.hiyo.top', 'https://codex.hiyo.top/', '#0F766E'),
  ('yes-hubniconico-com', 'yes.hubniconico.com', 'https://yes.hubniconico.com/', '#9333EA'),
  ('relay-nf-video', 'relay.nf.video', 'https://relay.nf.video/', '#2563EB'),
  ('zhangsan-yun', 'zhangsan.yun', 'https://zhangsan.yun/', '#7C3AED'),
  ('652token-shop', '652token.shop', 'https://652token.shop/', '#0EA5E9'),
  ('big-model-smart-agi-com', 'big-model.smart-agi.com', 'https://big-model.smart-agi.com/', '#16A34A'),
  ('code4ai-top', 'code4ai.top', 'https://code4ai.top/', '#EA580C'),
  ('hezu-ink', 'hezu.ink', 'https://hezu.ink/', '#DC2626'),
  ('nbgpt-xyz', 'nbgpt.xyz', 'http://nbgpt.xyz/', '#0F766E'),
  ('nekoapi-math4-org', 'nekoapi.math4.org', 'https://nekoapi.math4.org/', '#9333EA'),
  ('api-ggboys-xyz', 'api.ggboys.xyz', 'https://api.ggboys.xyz/', '#2563EB'),
  ('api-hualong-online', 'api.hualong.online', 'https://api.hualong.online/', '#7C3AED'),
  ('api-qpt-me', 'api.qpt.me', 'https://api.qpt.me/', '#0EA5E9'),
  ('api-router-team', 'api.router.team', 'https://api.router.team/', '#16A34A'),
  ('api-tokenrelayapi-com', 'api.tokenrelayapi.com', 'https://api.tokenrelayapi.com/', '#EA580C'),
  ('axis-yoga', 'axis.yoga', 'https://axis.yoga/', '#DC2626'),
  ('codex-cooskin-cc', 'codex.cooskin.cc', 'https://codex.cooskin.cc/', '#0F766E'),
  ('mhapi-cn', 'mhapi.cn', 'https://mhapi.cn/', '#9333EA'),
  ('opnai-top', 'opnai.top', 'https://opnai.top/', '#2563EB'),
  ('skyaidex-com', 'skyaidex.com', 'https://skyaidex.com/', '#7C3AED'),
  ('wapi-wintoken-dev', 'wapi.wintoken.dev', 'https://wapi.wintoken.dev/', '#0EA5E9'),
  ('ainipy-com', 'ainipy.com', 'https://www.ainipy.com/', '#16A34A'),
  ('zmzai-cn', 'zmzai.cn', 'https://zmzai.cn/', '#EA580C'),
  ('api-0-0-pro', 'api.0-0.pro', 'https://api.0-0.pro/', '#DC2626'),
  ('svip-fluapi-com', 'svip.fluapi.com', 'https://svip.fluapi.com/', '#0F766E'),
  ('little-api-top', 'little-api.top', 'https://little-api.top/', '#9333EA'),
  ('code-aifast-top', 'code.aifast.top', 'https://code.aifast.top/', '#2563EB'),
  ('superapi-buzz', 'superapi.buzz', 'https://superapi.buzz/', '#7C3AED'),
  ('us-api-umapis-com', 'us-api.umapis.com', 'https://us-api.umapis.com/', '#0EA5E9'),
  ('ai-jiuqingyunapi-top', 'ai.jiuqingyunapi.top', 'https://ai.jiuqingyunapi.top/', '#16A34A'),
  ('api-gettoken-dev', 'api.gettoken.dev', 'https://api.gettoken.dev/', '#EA580C'),
  ('dawnnode-com', 'dawnnode.com', 'https://dawnnode.com/', '#DC2626'),
  ('api-opennova-eu-cc', 'api.opennova.eu.cc', 'https://api.opennova.eu.cc/', '#0F766E'),
  ('api-t2-sg-freemodel-dev', 'api-t2-sg.freemodel.dev', 'https://api-t2-sg.freemodel.dev/', '#9333EA'),
  ('api-shiyunapi-com', 'api.shiyunapi.com', 'https://api.shiyunapi.com/', '#2563EB'),
  ('nixapi-com', 'nixapi.com', 'https://nixapi.com/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
