-- 500 冲刺批次：补足前台展示数到 500，继续避开临时入口和品牌混淆域名。
WITH new_providers(id, name, url, color) AS (
  VALUES
  ('xiaoruiera-top', 'xiaoruiera.top', 'https://www.xiaoruiera.top/', '#2563EB'),
  ('i-v1api-cc', 'i.v1api.cc', 'https://i.v1api.cc/', '#7C3AED'),
  ('1000-991239-xyz', '1000.991239.xyz', 'https://1000.991239.xyz/', '#0EA5E9'),
  ('1412520-cyou', '1412520.cyou', 'https://1412520.cyou/', '#16A34A'),
  ('91xhy-xyz', '91xhy.xyz', 'https://91xhy.xyz/', '#EA580C'),
  ('ai-jiegejd-eu-org', 'ai.jiegejd.eu.org', 'https://ai.jiegejd.eu.org/', '#DC2626'),
  ('ai-luckyos-top', 'ai.luckyos.top', 'http://ai.luckyos.top/', '#0F766E'),
  ('ai-manadmin-net', 'ai.manadmin.net', 'https://ai.manadmin.net/', '#9333EA'),
  ('ai-opendoor-sbs', 'ai.opendoor.sbs', 'https://ai.opendoor.sbs/', '#2563EB'),
  ('aiapi-siehe-net', 'aiapi.siehe.net', 'https://aiapi.siehe.net/', '#7C3AED'),
  ('aihub-firstshare-cn', 'aihub.firstshare.cn', 'https://aihub.firstshare.cn/', '#0EA5E9'),
  ('aiprogramming-cc', 'aiprogramming.cc', 'https://aiprogramming.cc/', '#16A34A'),
  ('aixlau-me', 'aixlau.me', 'https://aixlau.me/', '#EA580C'),
  ('allincoding-cc', 'allincoding.cc', 'https://allincoding.cc/', '#DC2626'),
  ('api-1a1api-top', 'api.1a1api.top', 'https://api.1a1api.top/', '#0F766E'),
  ('api-868986-xyz', 'api.868986.xyz', 'https://api.868986.xyz/', '#9333EA'),
  ('api-dxmcs-xin', 'api.dxmcs.xin', 'https://api.dxmcs.xin/', '#2563EB'),
  ('api-monkey-tools-cn', 'api.monkey-tools.cn', 'https://api.monkey-tools.cn/', '#7C3AED'),
  ('api-mouubox-com', 'api.mouubox.com', 'https://api.mouubox.com/', '#0EA5E9'),
  ('api-oaiapis-com', 'api.oaiapis.com', 'https://api.oaiapis.com/', '#16A34A'),
  ('api-relaymix-com', 'api.relaymix.com', 'https://api.relaymix.com/', '#EA580C'),
  ('api-schyler-top', 'api.schyler.top', 'https://api.schyler.top/', '#DC2626'),
  ('api-xiaohangyun-org', 'api.xiaohangyun.org', 'https://api.xiaohangyun.org/', '#0F766E'),
  ('api-xmirai-top', 'api.xmirai.top', 'https://api.xmirai.top/', '#9333EA'),
  ('api-zgonline-top', 'api.zgonline.top', 'https://api.zgonline.top/', '#2563EB'),
  ('api-zzq-uk', 'api.zzq.uk', 'https://api.zzq.uk/', '#7C3AED'),
  ('beecode-cc', 'beecode.cc', 'https://beecode.cc/', '#0EA5E9'),
  ('cloudlogicapi-com', 'cloudlogicapi.com', 'https://cloudlogicapi.com/', '#16A34A'),
  ('cn-gptapi-asia', 'cn.gptapi.asia', 'https://cn.gptapi.asia/', '#EA580C'),
  ('code-3rcd-com', 'code.3rcd.com', 'https://code.3rcd.com/', '#DC2626'),
  ('daboluo-zeabur-app', 'daboluo.zeabur.app', 'https://daboluo.zeabur.app/', '#0F766E'),
  ('direct-api-hyhawang-com', 'direct-api.hyhawang.com', 'https://direct-api.hyhawang.com/', '#9333EA'),
  ('directapi-eihhu-com', 'directapi.eihhu.com', 'https://directapi.eihhu.com/', '#2563EB'),
  ('hai-611996-xyz', 'hai.611996.xyz', 'https://hai.611996.xyz/', '#7C3AED'),
  ('hk-tokenlab-cc-cd', 'hk.tokenlab.cc.cd', 'https://hk.tokenlab.cc.cd/', '#0EA5E9'),
  ('hooye-api-top', 'hooye-api.top', 'https://hooye-api.top/', '#16A34A'),
  ('kekeshop-top', 'kekeshop.top', 'https://kekeshop.top/', '#EA580C'),
  ('kkkapi2234-top', 'kkkapi2234.top', 'https://kkkapi2234.top/', '#DC2626'),
  ('leleapi-top', 'leleapi.top', 'https://leleapi.top/', '#0F766E'),
  ('lgopenai-top', 'lgopenai.top', 'https://lgopenai.top/', '#9333EA'),
  ('llm-labx-ink', 'llm.labx.ink', 'https://llm.labx.ink/', '#2563EB'),
  ('longshang-pro', 'longshang.pro', 'https://longshang.pro/', '#7C3AED'),
  ('nbgpt-eu-cc', 'nbgpt.eu.cc', 'http://nbgpt.eu.cc/', '#0EA5E9'),
  ('nodeai-click', 'nodeai.click', 'https://nodeai.click/', '#16A34A'),
  ('open-codexcn-cn', 'open.codexcn.cn', 'https://open.codexcn.cn/', '#EA580C'),
  ('openapi-xz-wtf', 'openapi.xz.wtf', 'https://openapi.xz.wtf/', '#DC2626'),
  ('quotajet-com', 'quotajet.com', 'https://quotajet.com/', '#0F766E'),
  ('seeyon-api-net', 'seeyon-api.net', 'https://seeyon-api.net/', '#9333EA'),
  ('skybridge-api-com', 'skybridge-api.com', 'https://skybridge-api.com/', '#2563EB'),
  ('starport-openainotopen-com', 'starport.openainotopen.com', 'https://starport.openainotopen.com/', '#7C3AED')
)
INSERT OR IGNORE INTO providers (
  id, name, color, category, desc, brands, features, status, founded_at, url, online,
  input_price, output_price, sort_order, billing_type, supported_models, target_audience, free_quota,
  site_status, site_checked_at, site_status_code, site_error_days
)
SELECT
  id,
  name,
  color,
  '聚合中转',
  name || '：AI API 聚合中转服务入口，适合需要统一调用 OpenAI、Claude、Gemini、DeepSeek 等模型的开发者进行对比和小额测试。',
  '["OpenAI","Anthropic","Google","DeepSeek","Alibaba"]',
  '["聚合中转","统一 API 入口","公开榜单来源","适合小额测试","待商家认领补充"]',
  'ok',
  '',
  url,
  1,
  '',
  '',
  0,
  'pay_as_you_go',
  '["GPT 系列","Claude 系列","Gemini 系列","DeepSeek 系列","Qwen 系列"]',
  '通用',
  0,
  'ok',
  datetime('now','localtime'),
  200,
  0
FROM new_providers;
